// Generated by CoffeeScript 1.6.2
(function() {
  $.get("data/visas.csv", function(csv) {
    var countries, lines;

    lines = csv.split("\r");
    countries = lines[0].split(",").map(function(s) {
      return s.trim().toLowerCase();
    });
    console.log(countries);
    return $.get("data/final-topo.json", function(json) {
      var feature, name, _i, _len, _ref, _results;

      _ref = topojson.feature(json, json.objects.final).features;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        feature = _ref[_i];
        name = feature.properties.NAME;
        if (countries.indexOf(name.trim().toLowerCase()) > -1) {
          _results.push(console.log(name.toLowerCase()));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    });
  });

}).call(this);
